ecommerce/urls.py
from django.urls import path

from django.conf import settings



from .views import (checkout,productView,productDetail,
                    add_to_cart,remove_from_cart,cart_view,
                    update_view,remove_product_from_cart,
                    Checkout_view,PayementView,CreateCheckoutSession,
                    success_payment,cancel_payment,
                    stripe_webhook,
                    response_with_category,
                    search,
                    insert_comment,
                    )

app_name = "ecommerce"

urlpatterns = [
        path('', productView.as_view(), name='home'),
        path('checkout/', Checkout_view.as_view(), name='checkout'),
        path('product/<slug>/', productDetail.as_view(), name='productDetail'),
        path('add_to_cart/<slug>', add_to_cart, name="add_to_cart"),
        path('cart/<slug>&<quantity>', add_to_cart, name="cart_view_res"),
        path('remove_from_cart/<slug>',remove_from_cart,name='remove_from_cart'),
        path('cart/',cart_view,name='cart_view'),
        path('update_item/<pk>',update_view.as_view(),name="update_item"),
        path('delete_item/slg=<slug>',remove_product_from_cart,name="remove_product_from_cart_view"),
        path('payment/<payement_method>/',PayementView.as_view(),name='payment_method'),
        path('create_checkout_session/',CreateCheckoutSession.as_view(),name='create_checkout_session'),
        path('success/',success_payment,name='success_payment'),
        path('cancel/',cancel_payment,name='cancel_payment'),
        path('stripe/webhook/',stripe_webhook,name='stripe_webhook'),
        path('<category>/',response_with_category,name='response_with_category'),
        path('search',search,name='search_products'),
        path('insert_comment',insert_comment,name="insert_comment")
            ]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('persons', views.personsView, name='persons'),

]

ecommerce/forms.py
from django import forms
from django.db.models import fields
from django.forms.widgets import CheckboxInput, Widget
from .models import Product
from django_countries.fields import CountryField

'''
 title = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    category = models.CharField(choices=CATEGORIES, max_length=2)
    price = models.FloatField(default=0)
    discout_price = models.FloatField(null=True,blank=True)
    label  = models.CharField(choices=LABELS,max_length=15)
    slug = models.SlugField()
'''

PAYEMENT = (
    ('st','Stripe'),
    ('cr','credit cart'),
)


class productForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ['title','description','category','price',]



class CheckOutForm(forms.Form):
    street_adress = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'id':'street_adress',
        } ))

    apartment = forms.CharField(required=False,widget=forms.TextInput(attrs={
        'class':'form-control',
        
        'id':'apartment',
    }))

  
    country = CountryField(blank_label='(select country)').formfield(widget=forms.Select(attrs={
        'class':'custom-select d-block w-100',
        'id' : 'country'
        
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        
        'id':'zip',
    }))

    same_billing_adress = forms.BooleanField(required=False)

    save_info = forms.BooleanField(required=False)

    payment_options = forms.ChoiceField(widget=forms.RadioSelect,choices=PAYEMENT)
    
	

	

templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>imTel shop</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static '/mainTemplate/css/bootstrap.min.css'%}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static '/mainTemplate/css/mdb.min.css'%}"   rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static '/mainTemplate/css/style.min.css'%}"    rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'stars/stars.css'%}">
  <style type="text/css">

  
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
   {% block extra_head %}
   {% endblock %}
</head>

<body>

  <!-- Navbar -->
  {% block navbar %}

  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar mb-5">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'ecommerce:home' %}"  >
        <strong class="blue-text">imTel-Shop</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'ecommerce:home' %}" >Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">

            <a class="nav-link waves-effect" href="{% url 'ecommerce:checkout' %}" >Checkout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/"
              target="_blank">Landing Page</a>
          </li>

        </ul>
        {%block navDetails%}
        <!-- Right -->
        {%if user.is_authenticated %}
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'ecommerce:cart_view' %}" >
              <span class="badge red z-depth-1 mr-1"> {{request.user| cart_items_count }} </span>
              <i class="fas fa-shopping-cart"></i>

              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}" >
              <span class="badge green z-depth-1 mr-1" >Logout</span>
            </a>
            
          </li> 
          
        </ul>
        {%else%}
        <ul  class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}" >
              <span >Login</span>
            </a>
            
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}" >
              <span >Sign up</span>
            </a>
            
          </li>
        </ul>

        {%endif %}
        
        {%endblock navDetails%}


        
        
        
       

      </div>

    </div>
  </nav>

  {%endblock navbar %}


  {%for message in messages %}
  <div {%if message.tags %} class="alert alert-{{message.tags}}  alert-dismissible   animated fadeInDownBig"  {%endif%}   id="myAlert" role="alert">
    <a href = "#" class = "close" data-dismiss = "alert">&times;</a>
    
    <strong>Notification</strong> {{message}}
  </div>


  
  {%endfor%}

  <!-- Navbar -->

  {% block carousel %}
  <!--Carousel Wrapper-->


  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Dj Shop</strong> best quality and prices
              </h1>

              <p>
                <strong>Do your shopiing from your place with the best Offers</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

         

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  {% endblock carousel %}

    {% block mainContent%}
    {%for message in messages %}
    <div {%if message.tags %} class="alert alert-{{message.tags}}  alert-dismissible   animated fadeInDownBig"  {%endif%}   id="myAlert" role="alert">
      <a href = "#" class = "close" data-dismiss = "alert">&times;</a>
      
      <strong>Notification</strong> {{message}}
    </div>




	
	
    
    {%endfor%}
	
    {% endblock mainContent %}

    {% block extra_body %}
    {% endblock %}
	
	
  {%block footer%}
  <!--Footer-->
  <div class="container-fluid m-5 p-5" >
  </div>
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

  

 
    <!-- Social icons -->
    <div class="p-3 row justify-content-center align-items-center  ">
	
	
      <a class="pr-3 ml-3" href="https://github.com/ImadTel/App" target="_blank">
        <h5 > source code at </h5>
      </a>

      <a href="https://github.com/ImadTel/App" target="_blank">
       <span style="font-size:25px"><i class="fab fa-github mr-3"  > </i></span>
      </a>

      
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

  {%endblock footer%}
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'mainTemplate/js/jquery-3.4.1.min.js'  %}">  </script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'mainTemplate/js/popper.min.js'  %}"  ></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'mainTemplate/js/bootstrap.min.js'  %}"  ></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'mainTemplate/js/mdb.min.js'  %}"   ></script>

  <script type="text/javascript" href="{% static 'stars/stars.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">


    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

templates/home-page.html
{% extends 'base.html' %}
{%load media_root%}


{%block carousel%}
<div class="mt-5 pt-4">

</div>
{%endblock carousel %}


{%block mainContent %}
  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'ecommerce:home' %}">All
                <span class="sr-only">(current)</span>
              </a>
             
            </li>
            {% for k,v in categories %}
            <li class="nav-item"  >
              <a class="nav-link"  id="{{v}}"  name="categories" href="/ecommerce/{{k}}/"  >{{v}}</a>
            </li>
            {%endfor%}
           

          </ul>
          <!-- Links -->

          <form class="form-inline" method='GET' action="{% url 'ecommerce:search_products' %}">
            
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search_text" id="search_text">
              <input type="submit" class = "btn btn-primary"  value="submit">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->



     

      <div id="products">
        <section class="text-center mb-4">

          <!--Grid row-->
          <div class="row wow fadeIn"  id="itemsdiv">
  
            {%for item in object_list %}
                <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4" >
  
              <!--Card-->
              <div class="card  "    style="min-height:410px !important;max-height:430px !important;" >
  
                <!--Card image-->
                <div class="view overlay "  >
                  <img src="{{item.alt_image}}" class="card-img-top" style="min-height:60% !important;"
                    alt="product">
                  <a href="{{item.get_absolute_url}}">
                    <div class="mask rgba-white-slight"  ></div>
                  </a>
                </div>
                <!--Card image-->
  
                <!--Card content-->
				
                <div class="card-body text-center d-flex flex-column justify-content-end">
                  <!--Category & Title-->
                  <a href="" class="grey-text">
                    <h5>{{item.get_category_display}}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="" class="dark-grey-text">{{item.title}}
                        
                      </a>
                      <br><span class="badge badge-pill {{item.label}}-color">{{item.get_label_display}}</span>
                    </strong>
                  </h5>
  
                  <h4 class="font-weight-bold blue-text">
                    {% if item.discout_price %}
                    <span class="mr-1">
                     <del>{{item.discout_price}}$</del>
                     </span>
                     
                     <span class="mr-1">
                      {{item.price}}$
                      </span>
                    {% else %}
                   <span class="mr-1">{{item.price}}$</span>
                   {%endif%}
                    
                  </h4>
  
                </div>
				
                <!--Card content-->
  
              </div>
              <!--Card-->
  
            </div>
            <!--Grid column-->
  
            {%endfor %}
  
  
  
  
  
          </div>
          <!--Grid row-->
  
        </section>
        <!--Section: Products v.3-->
        {%if is_paginated%}
        <!--Pagination-->
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">
  
            <!--Arrow left-->
            {%if page_obj.has_previous %}
            <li class="page-item ">
              <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {%endif%}
            <li class="page-item active">
              <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
                <span class="sr-only">(current)</span>
              </a>
            </li>
           
  
            {%if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            {%endif%}
          </ul>
        </nav>
        <!--Pagination-->
        {%endif%}
      </div>
      </div>
      <!--Section: Products v.3-->
      
   
  </main>
  <!--Main layout-->
  

    {%for k,v in categories%}
    <script>
   
   
  document.getElementById("{{v}}").addEventListener('click',event =>{
  
  let ur = event.target.getAttribute('href')
  event.preventDefault()
  console.log("here from front end")
  $.ajax({
     url: ur,
     data: {
        
     },
     type: "GET",
     dataType : "html",
     success: function (data){
	 
      cards = document.getElementById('products')
      
         cards.innerHTML=data;
         
     },




    })
}



)
    </script>
    {%endfor%}


    
  
  

  
{% endblock mainContent %}

templates/porducts_list.html
{% extends "base.html" %}


{% block content %}
<h1>here are the products we have</h1>
{% for item in products_list %}


<h3> {{item.id}} -- {{item.title}}</h3>

{% endfor %}

{% endblock content %}

templates/product-page.html
{% extends "base.html" %}

{% load get_range %}
{% block carousel %}

{%endblock carousel %}




  {% block mainContent %}
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      {%for message in messages %}
      <div {%if message.tags %} class="alert alert-{{message.tags}}  alert-dismissible   animated fadeInDownBig"  {%endif%}   id="myAlert" role="alert">
        <a href = "#" class = "close" data-dismiss = "alert">&times;</a>
        
        <strong>Notification</strong> {{message}}
      </div>


      
      {%endfor%}
      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{object.alt_image}}" class="img-fluid" alt="{{object.title}}">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">{{object.get_label_display}}</span>
              </a>

            </div>

            <p class="lead">

                {% if object.discout_price %}
               <span class="mr-1">
                {{object.discout_price}}$
                </span>
                <span><del>{{object.price}}$</del></span>
               {% else %}
              <span>{{object.price}}$</span>
                {%endif%}

            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>
              {{object.description}}</p>
              <div class="d-flex justify-content-left" >
                <form class="d-flex justify-content-left"   method="POST"  action="{{object.get_add_to_cart_url }}"   >  {% csrf_token %}
                  <!-- Default input -->
                  <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px" name="quantity">

                  <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                    <i class="fas fa-shopping-cart ml-1"></i>
                  </button>
                  
                </form>
                  
                    <form class="d-flex justify-content-center" method="POST", action="{{object.get_remove_from_cart_url }}"> {% csrf_token %}
                    <button class="btn btn-danger btn-md my-0 p" >remove from cart 
                      <i class="fas fa-shopping-cart ml-1"></i>
                    </button>
                  
                </form>
              </div>
            
           


          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

              <!--Grid row-->
              <div class="row wow fadeIn">


                {%for image in images %}
                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <img src="{{image.alt_image}}"  class="img-fluid" alt="">

                </div>

                {%endfor%}
                <!--Grid column-->

                
           

              </div>
              <!--Grid row-->



      <hr>
      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-8 text-center">

          <h4 class="my-4 h4">reviews</h4>

          <!-- comments-->

          <div class="container">

          </div>
          <div id="comments_div">
            {%for comment in comments%}
            <div class="card p-3 mb-3 ">
              <div class="d-flex justify-content-start align-items-start ">
                  <div class="user d-flex flex-row align-items-center mr-2">
                     <img src="https://i.imgur.com/hczKIze.jpg" width="30" class="user-img rounded-circle mr-2"> 
                     <span><small class="font-weight-bold text-primary">{{comment.user}}</small>
                    
                    </div>

                    <div class="user d-flex flex-row justify-content-start  pt-2 align-items-start" style="min-width: 70% !important;" >
                      <small class="font-weight-bold" style="word-break: break-all;word-wrap: break-word; overflow: hidden !important;"><p>{{comment.content}}</p></small> </span> 
                    </div>    
                     
              </div>
              <div class="action d-flex justify-content-between mt-2 align-items-center">
                  <div class="reply px-4"> <small></small> <span class="dots"></span> <small></small> <span class="dots"></span> <small></small> </div>
                  <div class="icons align-items-center">
                    <small class="ml-2 mr-3 ">{{comment.rating}}</small>
                    {% for i in comment.rating|get_range %}
                     <i class="fa fa-star text-warning"></i>
                    
                     {%endfor%}
                     <i class="fa fa-check-circle-o check-icon"></i> 
                  </div>
                  



                
              </div>
          </div>
          {%endfor%}
          {%if user.is_authenticated%}
          <div class="card p-3 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                    <div class="user d-flex flex-row align-items-center">
                      <img src="https://i.imgur.com/hczKIze.jpg" width="30" class="user-img rounded-circle mr-1"> 
                      <span><h5 class="font-weight-bold text-primary">{{user.username}}</h5>
                        <small class="font-weight-bold"></small> </span> 
                        <small class="d-flex justify-content-center pl-3 ml-3">   
                          <fieldset class="rating p-2"> 
                            <input type="radio" id="star5" name="rating" value="5" /><label class="full" for="star5" title="Awesome - 5 stars"></label> 
                            <input type="radio" id="star4half" name="rating" value="4.5" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label> 
                            <input type="radio" id="star4" name="rating" value="4" /><label class="full" for="star4" title="Pretty good - 4 stars"></label> 
                            <input type="radio" id="star3half" name="rating" value="3.5" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
                            <input type="radio" id="star3" name="rating" value="3" /><label class="full" for="star3" title="Meh - 3 stars"></label> 
                            <input type="radio" id="star2half" name="rating" value="2.5" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
                            <input type="radio" id="star2" name="rating" value="2" /><label class="full" for="star2" title="Kinda bad - 2 stars"></label> 
                            <input type="radio" id="star1half" name="rating" value="1.5" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label> 
                            <input type="radio" id="star1" name="rating" value="1" /><label class="full" for="star1" title="Sucks big time - 1 star"></label> 
                            <input type="radio" id="starhalf" name="rating" value="0.5" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
                            <input type="radio" class="reset-option" name="rating" value="reset" /> 
                          </fieldset></small>
                      </div>
                  </div>

                    <form method="POST" action="{% url 'ecommerce:insert_comment' %}">
                      {%csrf_token %}
                      <div class="action d-flex justify-content-end mt-2 align-items-center">
                          
                        <textarea class="form-control" id="comment" name="comment"  style="max-width: 95% !important;" rows="5"></textarea>
                        <input type="hidden" id="myrating" name="myrating" class="myrating" value=0>
                        <input type="hidden" id="product_id" name="product_id" class="product_id" value="{{object.id}}">

                        <br>
                        
                    </div>

                    <div class="action d-flex justify-content-center mt-2 align-items-center">
                      <button type="submit" id="submit_comment" class="btn btn-secondary btn-block ml-4"  style="max-width: 30%;">send</button>
                  </div>
                    </form>

          </div>

            
        </div>
          
          {%endif%}
          </div>

          
         
          
            
      
          

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

     

    </div>



  </main>
  <script>
        document.getElementsByName("rating").forEach(element => element.addEventListener('click',event =>{
          var sim = $("input[name='rating']:checked").val();
          $(".myrating").val(sim)
         console.log( document.getElementById('myrating').getAttribute('value'))
}));





    document.getElementById("submit_comment").addEventListener('click',event=>{
      event.preventDefault();
      
      let comment  =  document.getElementById("comment").value;
      let rating = document.getElementById("myrating").getAttribute('value');
      let product_id =   document.getElementById("product_id").getAttribute('value');
      let csrf = $("input[name='csrfmiddlewaretoken']").val();
      
      console.log(csrf);
      $.ajax({
                type : "POST", 
                url: "{% url 'ecommerce:insert_comment' %}",
                dataType: "html",
                type: "POST",
                data: {
                  comment : comment,
                  myrating : rating,
                  product_id : product_id,
                  csrfmiddlewaretoken: csrf,
                  
                  
                    },
              success: function(data){
              
                console.log(data)
                   
                   document.getElementById('comments_div').innerHTML=data;
                   
                },

                error : function(xhr,errmsg,err) {
        console.log("tfaket"); 
      
                }
    });
  });
    


  </script>


  {%endblock mainContent %}